# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: netuno
      POSTGRES_PASSWORD: netuno
      POSTGRES_DB: netuno
    ports:
      - 5432:5432
d